- name: Install php-fpm
  apt:
    name: php-fpm
    state: present
  
- name: Install Composer
  apt:
    name: composer
    state: present

- name: Install PHP dependencies with Composer
  command: composer install
  args:
    chdir: /var/www/html/